# Generated by Django 5.2.10 on 2026-01-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proceso', models.TextField()),
                ('descripcion', models.TextField()),
                ('fuente', models.TextField()),
                ('formato', models.FileField(blank=True, null=True, upload_to='formatos/')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ejecucion', 'En ejecucion'), ('completado', 'Completado')], default='pendiente', max_length=90)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.direccion')),
                ('elaborado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_elaborados', to=settings.AUTH_USER_MODEL)),
                ('responsables', models.ManyToManyField(related_name='procesos_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['nombre_proceso'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('herramientas', models.TextField()),
                ('tiempo_dias_habiles', models.PositiveIntegerField()),
                ('documentos_generados', models.FileField(blank=True, null=True, upload_to='actividades/')),
                ('producto_servicio', models.TextField()),
                ('destinatario', models.CharField(max_length=255)),
                ('medio_entrega', models.TextField()),
                ('documento_final', models.FileField(blank=True, null=True, upload_to='finales/')),
                ('tipo_recurso', models.TextField()),
                ('descrip_recurso', models.TextField()),
                ('aprobada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
                ('responsables', models.ManyToManyField(related_name='actividades_responsables', to=settings.AUTH_USER_MODEL)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_revisadas', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='backend.proceso')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('proceso', 'numero')},
            },
        ),
    ]
