# Generated by Django 5.2.10 on 2026-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_actividad_aprobada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada')], default='pendiente', max_length=20),
        ),
    ]
